### ISSUE TITLE
Add slide to "respect the speaker"

### ISSUE THREAD

**Issue by clarkie** [lnug/slides#8]
Like they do during a rugby free kick or something can we add a slide at the beginning of the evening to remind lnuggers to respect the speaker by not talking during talks, interrupting, reminder to ask questions online or in the pub, etc 👍 

(more a reminder than anything else!) 😄

**Comment by msmichellegar** [comment]
Agree that it's good to clarify there is no Q&A (sometimes it happens accidentally) 🙌
